version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 3010:3010
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
