version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 27017:27017
    # TODO: volumes 추가 시 에러 -> 확인 필요
    # init 추가 필요
    #volumes:
    # - mongodb_data_container:/data/db
    #- ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 3010:3000
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      USER_HOSTNAME: ${USER_HOSTNAME}
    depends_on:
      - mongodb
# volumes:
#   mongodb_data_container:
